require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IsfitTabsController do

  # This should return the minimal set of attributes required to create a valid
  # IsfitTab. As you add validations to IsfitTab, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IsfitTabsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

#   describe "GET index" do
#     it "assigns all isfit_tabs as @isfit_tabs" do
#       isfit_tab = IsfitTab.create! valid_attributes
#       get :index, {}, valid_session
#       assigns(:isfit_tabs).should eq([isfit_tab])
#     end
#   end

#   describe "GET show" do
#     it "assigns the requested isfit_tab as @isfit_tab" do
#       isfit_tab = IsfitTab.create! valid_attributes
#       get :show, {:id => isfit_tab.to_param}, valid_session
#       assigns(:isfit_tab).should eq(isfit_tab)
#     end
#   end

#   describe "GET new" do
#     it "assigns a new isfit_tab as @isfit_tab" do
#       get :new, {}, valid_session
#       assigns(:isfit_tab).should be_a_new(IsfitTab)
#     end
#   end

#   describe "GET edit" do
#     it "assigns the requested isfit_tab as @isfit_tab" do
#       isfit_tab = IsfitTab.create! valid_attributes
#       get :edit, {:id => isfit_tab.to_param}, valid_session
#       assigns(:isfit_tab).should eq(isfit_tab)
#     end
#   end

#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new IsfitTab" do
#         expect {
#           post :create, {:isfit_tab => valid_attributes}, valid_session
#         }.to change(IsfitTab, :count).by(1)
#       end

#       it "assigns a newly created isfit_tab as @isfit_tab" do
#         post :create, {:isfit_tab => valid_attributes}, valid_session
#         assigns(:isfit_tab).should be_a(IsfitTab)
#         assigns(:isfit_tab).should be_persisted
#       end

#       it "redirects to the created isfit_tab" do
#         post :create, {:isfit_tab => valid_attributes}, valid_session
#         response.should redirect_to(IsfitTab.last)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns a newly created but unsaved isfit_tab as @isfit_tab" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         IsfitTab.any_instance.stub(:save).and_return(false)
#         post :create, {:isfit_tab => {  }}, valid_session
#         assigns(:isfit_tab).should be_a_new(IsfitTab)
#       end

#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         IsfitTab.any_instance.stub(:save).and_return(false)
#         post :create, {:isfit_tab => {  }}, valid_session
#         response.should render_template("new")
#       end
#     end
#   end

#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested isfit_tab" do
#         isfit_tab = IsfitTab.create! valid_attributes
#         # Assuming there are no other isfit_tabs in the database, this
#         # specifies that the IsfitTab created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         IsfitTab.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
#         put :update, {:id => isfit_tab.to_param, :isfit_tab => { "these" => "params" }}, valid_session
#       end

#       it "assigns the requested isfit_tab as @isfit_tab" do
#         isfit_tab = IsfitTab.create! valid_attributes
#         put :update, {:id => isfit_tab.to_param, :isfit_tab => valid_attributes}, valid_session
#         assigns(:isfit_tab).should be(isfit_tab)
#       end

#       it "redirects to the isfit_tab" do
#         isfit_tab = IsfitTab.create! valid_attributes
#         put :update, {:id => isfit_tab.to_param, :isfit_tab => valid_attributes}, valid_session
#         response.should redirect_to(isfit_tab)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns the isfit_tab as @isfit_tab" do
#         isfit_tab = IsfitTab.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         IsfitTab.any_instance.stub(:save).and_return(false)
#         put :update, {:id => isfit_tab.to_param, :isfit_tab => {  }}, valid_session
#         assigns(:isfit_tab).should be(isfit_tab)
#       end

#       it "re-renders the 'edit' template" do
#         isfit_tab = IsfitTab.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         IsfitTab.any_instance.stub(:save).and_return(false)
#         put :update, {:id => isfit_tab.to_param, :isfit_tab => {  }}, valid_session
#         response.should render_template("edit")
#       end
#     end
#   end

#   describe "DELETE destroy" do
#     it "destroys the requested isfit_tab" do
#       isfit_tab = IsfitTab.create! valid_attributes
#       expect {
#         delete :destroy, {:id => isfit_tab.to_param}, valid_session
#       }.to change(IsfitTab, :count).by(-1)
#     end

#     it "redirects to the isfit_tabs list" do
#       isfit_tab = IsfitTab.create! valid_attributes
#       delete :destroy, {:id => isfit_tab.to_param}, valid_session
#       response.should redirect_to(isfit_tabs_url)
#     end
#   end

end
