require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LayoutJobsController do

  # This should return the minimal set of attributes required to create a valid
  # LayoutJob. As you add validations to LayoutJob, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LayoutJobsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all layout_jobs as @layout_jobs" do
      layout_job = LayoutJob.create! valid_attributes
      get :index, {}, valid_session
      assigns(:layout_jobs).should eq([layout_job])
    end
  end

  describe "GET show" do
    it "assigns the requested layout_job as @layout_job" do
      layout_job = LayoutJob.create! valid_attributes
      get :show, {:id => layout_job.to_param}, valid_session
      assigns(:layout_job).should eq(layout_job)
    end
  end

  describe "GET new" do
    it "assigns a new layout_job as @layout_job" do
      get :new, {}, valid_session
      assigns(:layout_job).should be_a_new(LayoutJob)
    end
  end

  describe "GET edit" do
    it "assigns the requested layout_job as @layout_job" do
      layout_job = LayoutJob.create! valid_attributes
      get :edit, {:id => layout_job.to_param}, valid_session
      assigns(:layout_job).should eq(layout_job)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LayoutJob" do
        expect {
          post :create, {:layout_job => valid_attributes}, valid_session
        }.to change(LayoutJob, :count).by(1)
      end

      it "assigns a newly created layout_job as @layout_job" do
        post :create, {:layout_job => valid_attributes}, valid_session
        assigns(:layout_job).should be_a(LayoutJob)
        assigns(:layout_job).should be_persisted
      end

      it "redirects to the created layout_job" do
        post :create, {:layout_job => valid_attributes}, valid_session
        response.should redirect_to(LayoutJob.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved layout_job as @layout_job" do
        # Trigger the behavior that occurs when invalid params are submitted
        LayoutJob.any_instance.stub(:save).and_return(false)
        post :create, {:layout_job => {}}, valid_session
        assigns(:layout_job).should be_a_new(LayoutJob)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LayoutJob.any_instance.stub(:save).and_return(false)
        post :create, {:layout_job => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested layout_job" do
        layout_job = LayoutJob.create! valid_attributes
        # Assuming there are no other layout_jobs in the database, this
        # specifies that the LayoutJob created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LayoutJob.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => layout_job.to_param, :layout_job => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested layout_job as @layout_job" do
        layout_job = LayoutJob.create! valid_attributes
        put :update, {:id => layout_job.to_param, :layout_job => valid_attributes}, valid_session
        assigns(:layout_job).should eq(layout_job)
      end

      it "redirects to the layout_job" do
        layout_job = LayoutJob.create! valid_attributes
        put :update, {:id => layout_job.to_param, :layout_job => valid_attributes}, valid_session
        response.should redirect_to(layout_job)
      end
    end

    describe "with invalid params" do
      it "assigns the layout_job as @layout_job" do
        layout_job = LayoutJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LayoutJob.any_instance.stub(:save).and_return(false)
        put :update, {:id => layout_job.to_param, :layout_job => {}}, valid_session
        assigns(:layout_job).should eq(layout_job)
      end

      it "re-renders the 'edit' template" do
        layout_job = LayoutJob.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LayoutJob.any_instance.stub(:save).and_return(false)
        put :update, {:id => layout_job.to_param, :layout_job => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested layout_job" do
      layout_job = LayoutJob.create! valid_attributes
      expect {
        delete :destroy, {:id => layout_job.to_param}, valid_session
      }.to change(LayoutJob, :count).by(-1)
    end

    it "redirects to the layout_jobs list" do
      layout_job = LayoutJob.create! valid_attributes
      delete :destroy, {:id => layout_job.to_param}, valid_session
      response.should redirect_to(layout_jobs_url)
    end
  end

end
