require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MotdsController do

  # This should return the minimal set of attributes required to create a valid
  # Motd. As you add validations to Motd, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "msg" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MotdsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all motds as @motds" do
      motd = Motd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:motds).should eq([motd])
    end
  end

  describe "GET show" do
    it "assigns the requested motd as @motd" do
      motd = Motd.create! valid_attributes
      get :show, {:id => motd.to_param}, valid_session
      assigns(:motd).should eq(motd)
    end
  end

  describe "GET new" do
    it "assigns a new motd as @motd" do
      get :new, {}, valid_session
      assigns(:motd).should be_a_new(Motd)
    end
  end

  describe "GET edit" do
    it "assigns the requested motd as @motd" do
      motd = Motd.create! valid_attributes
      get :edit, {:id => motd.to_param}, valid_session
      assigns(:motd).should eq(motd)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Motd" do
        expect {
          post :create, {:motd => valid_attributes}, valid_session
        }.to change(Motd, :count).by(1)
      end

      it "assigns a newly created motd as @motd" do
        post :create, {:motd => valid_attributes}, valid_session
        assigns(:motd).should be_a(Motd)
        assigns(:motd).should be_persisted
      end

      it "redirects to the created motd" do
        post :create, {:motd => valid_attributes}, valid_session
        response.should redirect_to(Motd.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved motd as @motd" do
        # Trigger the behavior that occurs when invalid params are submitted
        Motd.any_instance.stub(:save).and_return(false)
        post :create, {:motd => { "msg" => "invalid value" }}, valid_session
        assigns(:motd).should be_a_new(Motd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Motd.any_instance.stub(:save).and_return(false)
        post :create, {:motd => { "msg" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested motd" do
        motd = Motd.create! valid_attributes
        # Assuming there are no other motds in the database, this
        # specifies that the Motd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Motd.any_instance.should_receive(:update_attributes).with({ "msg" => "MyString" })
        put :update, {:id => motd.to_param, :motd => { "msg" => "MyString" }}, valid_session
      end

      it "assigns the requested motd as @motd" do
        motd = Motd.create! valid_attributes
        put :update, {:id => motd.to_param, :motd => valid_attributes}, valid_session
        assigns(:motd).should eq(motd)
      end

      it "redirects to the motd" do
        motd = Motd.create! valid_attributes
        put :update, {:id => motd.to_param, :motd => valid_attributes}, valid_session
        response.should redirect_to(motd)
      end
    end

    describe "with invalid params" do
      it "assigns the motd as @motd" do
        motd = Motd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Motd.any_instance.stub(:save).and_return(false)
        put :update, {:id => motd.to_param, :motd => { "msg" => "invalid value" }}, valid_session
        assigns(:motd).should eq(motd)
      end

      it "re-renders the 'edit' template" do
        motd = Motd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Motd.any_instance.stub(:save).and_return(false)
        put :update, {:id => motd.to_param, :motd => { "msg" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested motd" do
      motd = Motd.create! valid_attributes
      expect {
        delete :destroy, {:id => motd.to_param}, valid_session
      }.to change(Motd, :count).by(-1)
    end

    it "redirects to the motds list" do
      motd = Motd.create! valid_attributes
      delete :destroy, {:id => motd.to_param}, valid_session
      response.should redirect_to(motds_url)
    end
  end

end
