require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParticipantQuotesController do
  login_user

  # This should return the minimal set of attributes required to create a valid
  # ParticipantQuote. As you add validations to ParticipantQuote, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParticipantQuotesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all participant_quotes as @participant_quotes" do
      participant_quote = ParticipantQuote.create! valid_attributes
      get :index, {}, valid_session
      assigns(:participant_quotes).should eq([participant_quote])
    end
  end

  describe "GET show" do
    it "assigns the requested participant_quote as @participant_quote" do
      participant_quote = ParticipantQuote.create! valid_attributes
      get :show, {:id => participant_quote.to_param}, valid_session
      assigns(:participant_quote).should eq(participant_quote)
    end
  end

  describe "GET new" do
    it "assigns a new participant_quote as @participant_quote" do
      get :new, {}, valid_session
      assigns(:participant_quote).should be_a_new(ParticipantQuote)
    end
  end

  describe "GET edit" do
    it "assigns the requested participant_quote as @participant_quote" do
      participant_quote = ParticipantQuote.create! valid_attributes
      get :edit, {:id => participant_quote.to_param}, valid_session
      assigns(:participant_quote).should eq(participant_quote)
    end
  end

  describe "POST create" do
    before(:each) { controller.stub(:current_user) { User.new } }
    
    describe "with valid params" do
      it "creates a new ParticipantQuote" do
        expect {
          post :create, {:participant_quote => valid_attributes}, valid_session
        }.to change(ParticipantQuote, :count).by(1)
      end

      it "assigns a newly created participant_quote as @participant_quote" do
        post :create, {:participant_quote => valid_attributes}, valid_session
        assigns(:participant_quote).should be_a(ParticipantQuote)
        assigns(:participant_quote).should be_persisted
      end

      it "redirects to the created participant_quote" do
        post :create, {:participant_quote => valid_attributes}, valid_session
        response.should redirect_to(ParticipantQuote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved participant_quote as @participant_quote" do
        # Trigger the behavior that occurs when invalid params are submitted
        ParticipantQuote.any_instance.stub(:save).and_return(false)
        post :create, {:participant_quote => {}}, valid_session
        assigns(:participant_quote).should be_a_new(ParticipantQuote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ParticipantQuote.any_instance.stub(:save).and_return(false)
        post :create, {:participant_quote => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested participant_quote" do
        participant_quote = ParticipantQuote.create! valid_attributes
        # Assuming there are no other participant_quotes in the database, this
        # specifies that the ParticipantQuote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ParticipantQuote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => participant_quote.to_param, :participant_quote => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested participant_quote as @participant_quote" do
        participant_quote = ParticipantQuote.create! valid_attributes
        put :update, {:id => participant_quote.to_param, :participant_quote => valid_attributes}, valid_session
        assigns(:participant_quote).should eq(participant_quote)
      end

      it "redirects to the participant_quote" do
        participant_quote = ParticipantQuote.create! valid_attributes
        put :update, {:id => participant_quote.to_param, :participant_quote => valid_attributes}, valid_session
        response.should redirect_to(participant_quote)
      end
    end

    describe "with invalid params" do
      it "assigns the participant_quote as @participant_quote" do
        participant_quote = ParticipantQuote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ParticipantQuote.any_instance.stub(:save).and_return(false)
        put :update, {:id => participant_quote.to_param, :participant_quote => {}}, valid_session
        assigns(:participant_quote).should eq(participant_quote)
      end

      it "re-renders the 'edit' template" do
        participant_quote = ParticipantQuote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ParticipantQuote.any_instance.stub(:save).and_return(false)
        put :update, {:id => participant_quote.to_param, :participant_quote => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested participant_quote" do
      participant_quote = ParticipantQuote.create! valid_attributes
      expect {
        delete :destroy, {:id => participant_quote.to_param}, valid_session
      }.to change(ParticipantQuote, :count).by(-1)
    end

    it "redirects to the participant_quotes list" do
      participant_quote = ParticipantQuote.create! valid_attributes
      delete :destroy, {:id => participant_quote.to_param}, valid_session
      response.should redirect_to(participant_quotes_url)
    end
  end

end
