require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StaticPagesController do
  login_user

  # This should return the minimal set of attributes required to create a valid
  # StaticPage. As you add validations to StaticPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all static_pages as @static_pages" do
      static_page = StaticPage.create! valid_attributes
      get :index
      assigns(:static_pages).should eq([static_page])
    end
  end

  describe "GET show" do
    it "assigns the requested static_page as @static_page" do
      static_page = StaticPage.create! valid_attributes
      get :show, :id => static_page.id.to_s
      assigns(:static_page).should eq(static_page)
    end
  end

  describe "GET new" do
    it "assigns a new static_page as @static_page" do
      get :new
      assigns(:static_page).should be_a_new(StaticPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested static_page as @static_page" do
      static_page = StaticPage.create! valid_attributes
      get :edit, :id => static_page.id.to_s
      assigns(:static_page).should eq(static_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StaticPage" do
        expect {
          post :create, :static_page => valid_attributes
        }.to change(StaticPage, :count).by(1)
      end

      it "assigns a newly created static_page as @static_page" do
        post :create, :static_page => valid_attributes
        assigns(:static_page).should be_a(StaticPage)
        assigns(:static_page).should be_persisted
      end

      it "redirects to the created static_page" do
        post :create, :static_page => valid_attributes
        response.should redirect_to(StaticPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved static_page as @static_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        StaticPage.any_instance.stub(:save).and_return(false)
        post :create, :static_page => {}
        assigns(:static_page).should be_a_new(StaticPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StaticPage.any_instance.stub(:save).and_return(false)
        post :create, :static_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested static_page" do
        static_page = StaticPage.create! valid_attributes
        # Assuming there are no other static_pages in the database, this
        # specifies that the StaticPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StaticPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => static_page.id, :static_page => {'these' => 'params'}
      end

      it "assigns the requested static_page as @static_page" do
        static_page = StaticPage.create! valid_attributes
        put :update, :id => static_page.id, :static_page => valid_attributes
        assigns(:static_page).should eq(static_page)
      end

      it "redirects to the static_page" do
        static_page = StaticPage.create! valid_attributes
        put :update, :id => static_page.id, :static_page => valid_attributes
        response.should redirect_to(static_page)
      end
    end

    describe "with invalid params" do
      it "assigns the static_page as @static_page" do
        static_page = StaticPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StaticPage.any_instance.stub(:save).and_return(false)
        put :update, :id => static_page.id.to_s, :static_page => {}
        assigns(:static_page).should eq(static_page)
      end

      it "re-renders the 'edit' template" do
        static_page = StaticPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StaticPage.any_instance.stub(:save).and_return(false)
        put :update, :id => static_page.id.to_s, :static_page => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested static_page" do
      static_page = StaticPage.create! valid_attributes
      expect {
        delete :destroy, :id => static_page.id.to_s
      }.to change(StaticPage, :count).by(-1)
    end

    it "redirects to the static_pages list" do
      static_page = StaticPage.create! valid_attributes
      delete :destroy, :id => static_page.id.to_s
      response.should redirect_to(static_pages_url)
    end
  end

end
