require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WikiCategoriesController do
  login_user


  # This should return the minimal set of attributes required to create a valid
  # WikiCategory. As you add validations to WikiCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {title: "WikiCat", deleted: false}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WikiCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wiki_categories as @wiki_categories" do
      wiki_category = WikiCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wiki_categories).should eq([wiki_category])
    end
  end

  describe "GET show" do
    it "assigns the requested wiki_category as @wiki_category" do
      wiki_category = WikiCategory.create! valid_attributes
      get :show, {:id => wiki_category.to_param}, valid_session
      assigns(:wiki_category).should eq(wiki_category)
    end
  end

  describe "GET new" do
    it "assigns a new wiki_category as @wiki_category" do
      get :new, {}, valid_session
      assigns(:wiki_category).should be_a_new(WikiCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested wiki_category as @wiki_category" do
      wiki_category = WikiCategory.create! valid_attributes
      get :edit, {:id => wiki_category.to_param}, valid_session
      assigns(:wiki_category).should eq(wiki_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WikiCategory" do
        expect {
          post :create, {:wiki_category => valid_attributes}, valid_session
        }.to change(WikiCategory, :count).by(1)
      end

      it "assigns a newly created wiki_category as @wiki_category" do
        post :create, {:wiki_category => valid_attributes}, valid_session
        assigns(:wiki_category).should be_a(WikiCategory)
        assigns(:wiki_category).should be_persisted
      end

      it "redirects to the created wiki_category" do
        post :create, {:wiki_category => valid_attributes}, valid_session
        response.should redirect_to(WikiCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wiki_category as @wiki_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        WikiCategory.any_instance.stub(:save).and_return(false)
        post :create, {:wiki_category => {}}, valid_session
        assigns(:wiki_category).should be_a_new(WikiCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WikiCategory.any_instance.stub(:save).and_return(false)
        post :create, {:wiki_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wiki_category" do
        wiki_category = WikiCategory.create! valid_attributes
        # Assuming there are no other wiki_categories in the database, this
        # specifies that the WikiCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WikiCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => wiki_category.to_param, :wiki_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested wiki_category as @wiki_category" do
        wiki_category = WikiCategory.create! valid_attributes
        put :update, {:id => wiki_category.to_param, :wiki_category => valid_attributes}, valid_session
        assigns(:wiki_category).should eq(wiki_category)
      end

      it "redirects to the wiki_category" do
        wiki_category = WikiCategory.create! valid_attributes
        put :update, {:id => wiki_category.to_param, :wiki_category => valid_attributes}, valid_session
        response.should redirect_to(wiki_category)
      end
    end

    describe "with invalid params" do
      it "assigns the wiki_category as @wiki_category" do
        wiki_category = WikiCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WikiCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => wiki_category.to_param, :wiki_category => {}}, valid_session
        assigns(:wiki_category).should eq(wiki_category)
      end

      it "re-renders the 'edit' template" do
        wiki_category = WikiCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WikiCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => wiki_category.to_param, :wiki_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wiki_category" do
      wiki_category = WikiCategory.create! valid_attributes
      delete :destroy, {:id => wiki_category.to_param}, valid_session
      WikiCategory.find(wiki_category.id).deleted.should be true
    end

    it "redirects to the wiki_categories list" do
      wiki_category = WikiCategory.create! valid_attributes
      delete :destroy, {:id => wiki_category.to_param}, valid_session
      response.should redirect_to(wiki_categories_url)
    end
  end

end
