require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WikiPagesController do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # WikiPage. As you add validations to WikiPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {title: "WikiPage"}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WikiPagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wiki_pages as @wiki_pages" do
      wiki_page = WikiPage.create!({title: "getting-started"})
      get :index, {}, valid_session
      assigns(:wiki_page).should eq(wiki_page)
    end
  end

  describe "GET show" do
    it "assigns the requested wiki_page as @wiki_page" do
      wiki_page = WikiPage.create! valid_attributes
      get :show, {:id => wiki_page.to_param}, valid_session
      assigns(:wiki_page).should eq(wiki_page)
    end
  end

  describe "GET new" do
    it "assigns a new wiki_page as @wiki_page" do
      get :new, {}, valid_session
      assigns(:wiki_page).should be_a_new(WikiPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested wiki_page as @wiki_page" do
      wiki_page = WikiPage.create! valid_attributes
      get :edit, {:id => wiki_page.to_param}, valid_session
      assigns(:wiki_page).should eq(wiki_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WikiPage" do
        expect {
          post :create, {:wiki_page => valid_attributes}, valid_session
        }.to change(WikiPage, :count).by(1)
      end

      it "assigns a newly created wiki_page as @wiki_page" do
        post :create, {:wiki_page => valid_attributes}, valid_session
        assigns(:wiki_page).should be_a(WikiPage)
        assigns(:wiki_page).should be_persisted
      end

      it "redirects to the created wiki_page" do
        post :create, {:wiki_page => valid_attributes}, valid_session
        response.should redirect_to(WikiPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wiki_page as @wiki_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        WikiPage.any_instance.stub(:save).and_return(false)
        post :create, {:wiki_page => {}}, valid_session
        assigns(:wiki_page).should be_a_new(WikiPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WikiPage.any_instance.stub(:save).and_return(false)
        post :create, {:wiki_page => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do

      it "assigns a new wiki_page as @wiki_page with current wiki_page as parrent" do
        wiki_page = WikiPage.create! valid_attributes
        put :update, {:id => wiki_page.to_param, :wiki_page => valid_attributes}, valid_session
        assigns(:wiki_page).should eq(wiki_page.child_page)
      end

      it "redirects to the child wiki_page" do
        wiki_page = WikiPage.create! valid_attributes
        put :update, {:id => wiki_page.to_param, :wiki_page => valid_attributes}, valid_session
        response.should redirect_to(wiki_page.child_page)
      end
    end

    describe "with invalid params" do
      it "assigns a new wiki_page as @wiki_page and set the correct wiki_page_id" do
        wiki_page = WikiPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WikiPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => wiki_page.to_param, :wiki_page => {}}, valid_session
        assigns(:wiki_page).should be_a_new(WikiPage)
        assigns(:wiki_page).wiki_page_id.should eq(wiki_page.id)
      end

      it "re-renders the 'edit' template" do
        wiki_page = WikiPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WikiPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => wiki_page.to_param, :wiki_page => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wiki_page" do
      wiki_page = WikiPage.create! valid_attributes
      delete :destroy, {:id => wiki_page.to_param}, valid_session
      WikiPage.find(wiki_page.id).deleted.should be true
    end

    it "redirects to the wiki_pages list" do
      wiki_page = WikiPage.create! valid_attributes
      delete :destroy, {:id => wiki_page.to_param}, valid_session
      response.should redirect_to(wiki_pages_url)
    end
  end

end
